### ISSUE TITLE
Could not find CIDetector

### ISSUE THREAD

**Issue by kyle-ssg** [evermeer/EVFaceTracker#3]
Hey, apologies for my lack of knowledge in Objective C - I'm actually looking at if it's possible to port this to ReactNative. Running this in my project I get : 

```
/Users/kyle/rnfacetracking/ios/Pods/Headers/Public/EVFaceTracker/EVFaceTracker.h:22:5: Unknown type name 'CIDetector'
```

I fixed this by adding the following to EvFaceTracker.h 
```
#import <CoreImage/CoreImage.h>
```

Is this correct or am I missing something?

**Comment by evermeer** [comment]
Hmm... I was under the impression that AVFoundation did that by default. I do see that indeed it's required, but in my demo I don't have to import it. But I can also add it without any problems. So I will do that and push a new version later today.

**Comment by kyle-ssg** [comment]
Cool stuff, all worked once I added that - really cool lib :)
