### ISSUE TITLE
is it possible 10 feet distance mesaure?

### ISSUE THREAD

**Issue by vnanaware** [evermeer/EVFaceTracker#6]
Hello,

     This is good demo to distance measure but it's measuring now only 2feet I want to upto 10 feet how it is possible?

Thanks & Ragards,
Vishal.

**Comment by evermeer** [comment]
Distance measuring is based on the build in face detection feature.
Calculating the angle to the device will work well no matter the distance as long as it's able to detect the face.
Calculating the distance is always an estimate based on the rectangle that is given by the device. 
When you move the device further than 2 feet the rectangle won't change much and the estimate will probably be off.
The camera is not a great tool for creating measurements.
In newer iPhones there is a lidar embedded which will give better results.
But I have no idea how you could make use of that.
